version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=spring_test
      - POSTGRES_PASSWORD=spring_test
      - POSTGRES_DB=spring_test
